# Generated by Django 5.2.17 on 2026-08-29 17:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_common_misconceptions_and_more'),
        ('provenance', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProvenanceEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('lesson_created', 'Lesson created'), ('ai_draft_generated', 'AI draft generated'), ('ai_review_completed', 'AI review completed'), ('teacher_accepted', 'Teacher accepted'), ('teacher_edited', 'Teacher edited'), ('teacher_rejected', 'Teacher rejected'), ('lesson_finalized', 'Lesson finalized')], max_length=32)),
                ('source', models.CharField(blank=True, help_text='Actor or origin for this event, such as teacher or an AI provider.', max_length=50)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lesson_provenance_events', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='provenance_events', to='lessons.lesson')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['lesson', 'created_at'], name='provenance__lesson__a01737_idx')],
            },
        ),
    ]
