# Generated by Django 5.2.17 on 2026-09-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('provenance', '0002_provenanceevent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provenanceevent',
            name='event_type',
            field=models.CharField(choices=[('lesson_created', 'Lesson created'), ('ai_draft_generated', 'AI draft generated'), ('ai_review_completed', 'AI review completed'), ('teacher_accepted', 'Teacher accepted'), ('teacher_edited', 'Teacher edited'), ('teacher_rejected', 'Teacher rejected'), ('lesson_finalized', 'Lesson finalized'), ('lesson_updated', 'Lesson updated by teacher'), ('lesson_published', 'Lesson published')], max_length=32),
        ),
    ]
