# Generated by Django 5.2.17 on 2026-09-01 22:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0002_physicsmisconception'),
        ('students', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentMisconception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('confidence', models.CharField(choices=[('low', 'Low'), ('medium', 'Medium'), ('high', 'High')], default='low', max_length=8)),
                ('status', models.CharField(choices=[('candidate', 'Candidate'), ('confirmed_by_teacher', 'Confirmed by teacher'), ('resolved', 'Resolved'), ('dismissed', 'Dismissed')], default='candidate', max_length=24)),
                ('first_observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('last_observed_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('observation_count', models.PositiveIntegerField(default=0)),
                ('evidence_summary', models.CharField(blank=True, default='', max_length=500)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('teacher_note', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misconception_decisions', to=settings.AUTH_USER_MODEL)),
                ('misconception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='student_observations', to='physics.physicsmisconception')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconceptions', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-last_observed_at'],
            },
        ),
        migrations.CreateModel(
            name='MisconceptionEvidence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('rule', 'Rule'), ('ai', 'AI')], max_length=8)),
                ('detector', models.CharField(blank=True, default='', help_text='Rule code or prompt version that produced this signal.', max_length=64)),
                ('excerpt', models.CharField(max_length=500)),
                ('reasoning', models.CharField(blank=True, default='', max_length=500)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('learning_evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misconception_evidence', to='students.learningevidence')),
                ('tutor_message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='misconception_evidence', to='students.tutormessage')),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evidence', to='students.studentmisconception')),
            ],
            options={
                'ordering': ['created_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='studentmisconception',
            index=models.Index(fields=['status', 'last_observed_at'], name='students_st_status_f2ba8c_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentmisconception',
            constraint=models.UniqueConstraint(fields=('student', 'misconception'), name='uniq_student_misconception'),
        ),
        migrations.AddIndex(
            model_name='misconceptionevidence',
            index=models.Index(fields=['observation', 'created_at'], name='students_mi_observa_26383d_idx'),
        ),
    ]
