# Generated by Django 5.2.17 on 2026-09-01 23:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_common_misconceptions_and_more'),
        ('physics', '0003_physicssimulation'),
        ('students', '0002_studentmisconception_misconceptionevidence_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExperimentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('prediction', models.TextField(blank=True, default='')),
                ('observation', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('mass_kg', models.FloatField(blank=True, null=True)),
                ('force_n', models.FloatField(blank=True, null=True)),
                ('acceleration_m_s2', models.FloatField(blank=True, null=True)),
                ('parameters', models.JSONField(blank=True, default=dict, help_text='Structured experiment context recomputed on the server.')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.AddField(
            model_name='learningevidence',
            name='context',
            field=models.JSONField(blank=True, default=dict, help_text='Optional structured context, e.g. deterministic experiment parameters {simulation, mass_kg, force_n, acceleration_m_s2}.'),
        ),
        migrations.AlterField(
            model_name='learningevidence',
            name='kind',
            field=models.CharField(choices=[('question_asked', 'Question asked'), ('practice_attempted', 'Practice attempted'), ('prediction_submitted', 'Prediction submitted'), ('experiment_observed', 'Experiment observed'), ('explanation_submitted', 'Explanation submitted')], max_length=32),
        ),
        migrations.AlterField(
            model_name='learningevidence',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='learning_evidence', to='lessons.lesson'),
        ),
        migrations.AddIndex(
            model_name='learningevidence',
            index=models.Index(fields=['student', 'kind'], name='students_le_student_f97631_idx'),
        ),
        migrations.AddField(
            model_name='experimentattempt',
            name='lesson',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_attempts', to='lessons.lesson'),
        ),
        migrations.AddField(
            model_name='experimentattempt',
            name='session',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='experiment_attempts', to='students.tutorsession'),
        ),
        migrations.AddField(
            model_name='experimentattempt',
            name='simulation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='physics.physicssimulation'),
        ),
        migrations.AddField(
            model_name='experimentattempt',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='experiment_attempts', to='students.studentprofile'),
        ),
        migrations.AddIndex(
            model_name='experimentattempt',
            index=models.Index(fields=['student', 'simulation'], name='students_ex_student_927b53_idx'),
        ),
        migrations.AddIndex(
            model_name='experimentattempt',
            index=models.Index(fields=['simulation', 'started_at'], name='students_ex_simulat_4eecf0_idx'),
        ),
    ]
