# Generated by Django 5.2.17 on 2026-09-02 08:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_common_misconceptions_and_more'),
        ('physics', '0003_physicssimulation'),
        ('students', '0003_experimentattempt_learningevidence_context_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='PracticeAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_key', models.CharField(max_length=100)),
                ('question_type', models.CharField(choices=[('numeric', 'Numeric'), ('multiple_choice', 'Multiple choice'), ('free_text', 'Free text')], max_length=20)),
                ('question_prompt', models.CharField(help_text='Snapshot of the question as it was shown for this attempt.', max_length=500)),
                ('answer_text', models.CharField(help_text='Exactly what the student submitted (a number as text, or a choice label).', max_length=500)),
                ('is_correct', models.BooleanField(blank=True, help_text='Deterministic verdict. NULL for free-text questions that have no single answer.', null=True)),
                ('attempt_number', models.PositiveSmallIntegerField(default=1, help_text='1-based, per (student, lesson, question_key). A retry increments it.')),
                ('expected_display', models.CharField(blank=True, default='', help_text='Human-readable expected answer resolved from trusted lesson data at attempt time. A teacher reference only; never used to re-grade.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_attempts', to='physics.physicsconcept')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_attempts', to='students.learningevidence')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='lessons.lesson')),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice_attempts', to='students.tutorsession')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='practice_attempts', to='students.studentprofile')),
            ],
            options={
                'ordering': ['created_at', 'id'],
                'indexes': [models.Index(fields=['student', 'lesson', 'question_key'], name='students_pr_student_ce5b9a_idx'), models.Index(fields=['lesson', 'created_at'], name='students_pr_lesson__ef5d63_idx'), models.Index(fields=['student', 'created_at'], name='students_pr_student_8fa065_idx')],
            },
        ),
    ]
