# Generated by Django 5.2.17 on 2026-09-04 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0004_practiceattempt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningevidence',
            name='kind',
            field=models.CharField(choices=[('question_asked', 'Question asked'), ('practice_attempted', 'Practice attempted'), ('prediction_submitted', 'Prediction submitted'), ('experiment_observed', 'Experiment observed'), ('explanation_submitted', 'Explanation submitted'), ('assessment_attempted', 'Assessment attempted')], max_length=32),
        ),
    ]
