# Generated by Django 5.2.17 on 2026-09-04 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0005_misconceptionrecoverypath_and_more'),
        ('students', '0005_alter_learningevidence_kind'),
    ]

    operations = [
        migrations.AlterField(
            model_name='learningevidence',
            name='kind',
            field=models.CharField(choices=[('question_asked', 'Question asked'), ('practice_attempted', 'Practice attempted'), ('prediction_submitted', 'Prediction submitted'), ('experiment_observed', 'Experiment observed'), ('explanation_submitted', 'Explanation submitted'), ('assessment_attempted', 'Assessment attempted'), ('recovery_activity_completed', 'Recovery activity completed')], max_length=32),
        ),
        migrations.CreateModel(
            name='StudentMisconceptionRecovery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('observation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recoveries', to='students.studentmisconception')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recoveries', to='physics.misconceptionrecoverypath')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='misconception_recoveries', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='StudentRecoveryActivityCompletion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.CharField(blank=True, default='', max_length=20)),
                ('completed_at', models.DateTimeField(auto_now_add=True)),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='physics.misconceptionrecoveryactivity')),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='students.learningevidence')),
                ('recovery', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_completions', to='students.studentmisconceptionrecovery')),
            ],
            options={
                'ordering': ['completed_at', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='studentmisconceptionrecovery',
            index=models.Index(fields=['student', 'completed_at'], name='students_st_student_8ecfbe_idx'),
        ),
        migrations.AddConstraint(
            model_name='studentmisconceptionrecovery',
            constraint=models.UniqueConstraint(condition=models.Q(('completed_at__isnull', True)), fields=('student', 'observation'), name='uniq_active_recovery_per_observation'),
        ),
        migrations.AddConstraint(
            model_name='studentrecoveryactivitycompletion',
            constraint=models.UniqueConstraint(fields=('recovery', 'activity'), name='uniq_recovery_activity_completion'),
        ),
    ]
