# Generated by Django 5.2.17 on 2026-09-20 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0007_alter_studentrecoveryactivitycompletion_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='tutorsession',
            name='socratic_mode',
            field=models.BooleanField(default=False, help_text='When on, the tutor sticks to guiding questions instead of direct answers/explanations for this session, even when asked directly -- the student can still ask it to just explain.'),
        ),
    ]
