# Generated by Django 5.2.17 on 2026-09-04 17:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0003_alter_lesson_common_misconceptions_and_more'),
        ('physics', '0003_physicssimulation'),
        ('students', '0005_alter_learningevidence_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Assessment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, help_text='Stable, student-safe identifier used in learning-evidence records.', max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='physics.physicsconcept')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments_created', to=settings.AUTH_USER_MODEL)),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessments', to='lessons.lesson')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attempts', to='assessments.assessment')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_attempts', to='students.studentprofile')),
            ],
            options={
                'ordering': ['-started_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentQuestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.PositiveSmallIntegerField(default=0)),
                ('assessment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assessment_questions', to='assessments.assessment')),
            ],
            options={
                'ordering': ['position', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AssessmentAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('answer_text', models.CharField(max_length=500)),
                ('is_correct', models.BooleanField(blank=True, null=True)),
                ('attempted_at', models.DateTimeField(auto_now_add=True)),
                ('evidence', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_answers', to='students.learningevidence')),
                ('attempt', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='assessments.assessmentattempt')),
                ('assessment_question', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='answers', to='assessments.assessmentquestion')),
            ],
            options={
                'ordering': ['attempted_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='QuestionBankItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.SlugField(help_text="Stable identifier, unique across the whole question bank -- never a positional index like 'q1'.", max_length=120, unique=True)),
                ('question_type', models.CharField(choices=[('numeric', 'Numeric'), ('multiple_choice', 'Multiple choice')], max_length=20)),
                ('prompt', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', help_text='Describes the question, not the student.', max_length=10)),
                ('choices', models.JSONField(blank=True, default=list)),
                ('correct_choice', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('expected_value', models.FloatField(blank=True, null=True)),
                ('expected_unit', models.CharField(blank=True, default='', max_length=40)),
                ('tolerance', models.FloatField(blank=True, null=True)),
                ('hint', models.TextField(blank=True, default='')),
                ('explanation', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive questions are hidden from new assessments; past attempts are unaffected.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(blank=True, help_text='Optional link into the Physics concept graph.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='question_bank_items', to='physics.physicsconcept')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='question_bank_items', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddField(
            model_name='assessmentquestion',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='assessment_questions', to='assessments.questionbankitem'),
        ),
        migrations.AddField(
            model_name='assessment',
            name='questions',
            field=models.ManyToManyField(related_name='assessments', through='assessments.AssessmentQuestion', to='assessments.questionbankitem'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['student', 'assessment'], name='assessments_student_dca0da_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentattempt',
            index=models.Index(fields=['assessment', 'started_at'], name='assessments_assessm_8fa08d_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentattempt',
            constraint=models.UniqueConstraint(fields=('student', 'assessment'), name='uniq_student_assessment_attempt'),
        ),
        migrations.AddIndex(
            model_name='assessmentanswer',
            index=models.Index(fields=['attempt', 'attempted_at'], name='assessments_attempt_87ef1f_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentanswer',
            constraint=models.UniqueConstraint(fields=('attempt', 'assessment_question'), name='uniq_attempt_question_answer'),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['question_type', 'is_active'], name='assessments_questio_71e3fa_idx'),
        ),
        migrations.AddIndex(
            model_name='questionbankitem',
            index=models.Index(fields=['concept', 'is_active'], name='assessments_concept_570bb9_idx'),
        ),
        migrations.AddIndex(
            model_name='assessmentquestion',
            index=models.Index(fields=['assessment', 'position'], name='assessments_assessm_d7d4b3_idx'),
        ),
        migrations.AddConstraint(
            model_name='assessmentquestion',
            constraint=models.UniqueConstraint(fields=('assessment', 'question'), name='uniq_assessment_question'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['status', '-created_at'], name='assessments_status_be3ff1_idx'),
        ),
        migrations.AddIndex(
            model_name='assessment',
            index=models.Index(fields=['concept', 'status'], name='assessments_concept_4ae43a_idx'),
        ),
    ]
