# Generated by Django 5.2.17 on 2026-09-19 22:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='assessmentanswer',
            name='reviewed_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assessment_answers_reviewed', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='assessmentanswer',
            name='teacher_feedback',
            field=models.CharField(blank=True, default='', max_length=1000),
        ),
        migrations.AlterField(
            model_name='assessmentanswer',
            name='answer_text',
            field=models.CharField(max_length=4000),
        ),
        migrations.AlterField(
            model_name='assessmentanswer',
            name='is_correct',
            field=models.BooleanField(blank=True, help_text='Null means ungraded -- always true for a fresh free-response answer.', null=True),
        ),
        migrations.AlterField(
            model_name='questionbankitem',
            name='question_type',
            field=models.CharField(choices=[('numeric', 'Numeric'), ('multiple_choice', 'Multiple choice'), ('free_response', 'Free response')], max_length=20),
        ),
    ]
