# Generated by Django 5.2.17 on 2026-08-26 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsConcept',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, unique=True)),
                ('slug', models.SlugField(max_length=160, unique=True)),
                ('description', models.TextField(help_text='A concise, scientifically accurate explanation of the concept.')),
                ('topic', models.CharField(db_index=True, help_text='Broad Physics category, such as Kinematics or Dynamics.', max_length=80)),
                ('difficulty', models.CharField(choices=[('foundational', 'Foundational'), ('introductory', 'Introductory'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='foundational', max_length=20)),
                ('common_misconceptions', models.JSONField(blank=True, default=list, help_text='Common incorrect ideas associated with this concept.')),
                ('prerequisites', models.JSONField(blank=True, default=list, help_text='Names of concepts learners should understand first.')),
                ('equations', models.JSONField(blank=True, default=list, help_text='Relevant equations expressed as readable strings.')),
                ('si_units', models.JSONField(blank=True, default=list, help_text='Relevant SI units expressed as readable strings.')),
                ('is_active', models.BooleanField(default=True, help_text='Inactive concepts are retained but excluded from normal use.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Physics concept',
                'verbose_name_plural': 'Physics concepts',
                'ordering': ['topic', 'name'],
            },
        ),
    ]
