# Generated by Django 5.2.17 on 2026-09-01 22:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsMisconception',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='Stable machine identifier, e.g. FREE_FALL_MASS_ACCELERATION.', max_length=64, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(help_text='Cautious, educational summary of the possible misunderstanding. Phrase it as something a learner *may* believe, never as a verdict.')),
                ('detection_guidance', models.TextField(blank=True, default='', help_text='Reasoning patterns or statements that may suggest this confusion.')),
                ('intervention_guidance', models.TextField(blank=True, default='', help_text='A teaching move the tutor can use, e.g. a controlled comparison.')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('physics_concept', models.ForeignKey(help_text='The concept this misconception most directly distorts.', on_delete=django.db.models.deletion.PROTECT, related_name='misconceptions', to='physics.physicsconcept')),
            ],
            options={
                'verbose_name': 'Physics misconception',
                'verbose_name_plural': 'Physics misconceptions',
                'ordering': ['code'],
            },
        ),
    ]
