# Generated by Django 5.2.17 on 2026-09-01 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0002_physicsmisconception'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsSimulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=80, unique=True)),
                ('title', models.CharField(max_length=150)),
                ('description', models.TextField(blank=True, default='')),
                ('simulation_type', models.CharField(choices=[('newtons_second_law', "Newton's Second Law")], help_text='Selects which client-side simulation and template to render.', max_length=40)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('concept', models.ForeignKey(help_text='The concept this simulation lets a student explore.', on_delete=django.db.models.deletion.PROTECT, related_name='simulations', to='physics.physicsconcept')),
            ],
            options={
                'verbose_name': 'Physics simulation',
                'verbose_name_plural': 'Physics simulations',
                'ordering': ['title'],
            },
        ),
    ]
