# Generated by Django 5.2.17 on 2026-09-04 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0003_physicssimulation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicssimulation',
            name='simulation_type',
            field=models.CharField(choices=[('newtons_second_law', "Newton's Second Law"), ('kinematics', 'Kinematics')], help_text='Selects which client-side simulation and template to render.', max_length=40),
        ),
    ]
