# Generated by Django 5.2.17 on 2026-09-04 23:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0004_alter_physicssimulation_simulation_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='MisconceptionRecoveryPath',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150)),
                ('student_summary', models.CharField(help_text="Student-facing framing shown on the recovery page. Plain, encouraging language -- never the misconception's name or code.", max_length=300)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('misconception', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recovery_paths', to='physics.physicsmisconception')),
            ],
            options={
                'verbose_name': 'Misconception recovery path',
                'verbose_name_plural': 'Misconception recovery paths',
                'ordering': ['misconception__code', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MisconceptionRecoveryActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(help_text='1-based position in the path. Activities are completed in this order.')),
                ('activity_type', models.CharField(choices=[('physics_lab', 'Physics Lab'), ('tutor_reflection', 'Tutor reflection'), ('concept_check', 'Concept check')], max_length=32)),
                ('label', models.CharField(help_text='Short student-facing step title.', max_length=150)),
                ('instructions', models.TextField(blank=True, default='', help_text='Student-facing framing for this step (Think / Predict prompts etc.).')),
                ('check_prompt', models.CharField(blank=True, default='', help_text="Required for a 'concept_check' step.", max_length=300)),
                ('check_choices', models.JSONField(blank=True, default=list, help_text="Plain list of answer choice strings for a 'concept_check' step.")),
                ('check_correct_choice', models.PositiveSmallIntegerField(blank=True, help_text='0-based index into check_choices.', null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('simulation', models.ForeignKey(blank=True, help_text="Required for a 'physics_lab' step; unused otherwise.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='physics.physicssimulation')),
                ('path', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='physics.misconceptionrecoverypath')),
            ],
            options={
                'verbose_name': 'Misconception recovery activity',
                'verbose_name_plural': 'Misconception recovery activities',
                'ordering': ['path', 'order', 'id'],
                'constraints': [models.UniqueConstraint(fields=('path', 'order'), name='uniq_recovery_activity_order')],
            },
        ),
    ]
