# Generated by Django 5.2.17 on 2026-09-12 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0005_misconceptionrecoverypath_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicssimulation',
            name='simulation_type',
            field=models.CharField(choices=[('newtons_second_law', "Newton's Second Law"), ('kinematics', 'Kinematics'), ('projectile_motion', 'Projectile Motion')], help_text='Selects which client-side simulation and template to render.', max_length=40),
        ),
    ]
