# Generated by Django 5.2.17 on 2026-09-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0014_alter_physicssimulation_simulation_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='physicssimulation',
            name='simulation_type',
            field=models.CharField(choices=[('newtons_second_law', "Newton's Second Law"), ('kinematics', 'Kinematics'), ('projectile_motion', 'Projectile Motion'), ('circular_motion', 'Circular Motion'), ('simple_harmonic_motion', 'Simple Harmonic Motion'), ('momentum_collision', 'Momentum and Collisions'), ('energy_incline', 'Energy on an Incline'), ('orbital_motion', 'Orbital Motion'), ('series_parallel_circuit', 'Series and Parallel Circuits'), ('coulombs_law', "Coulomb's Law"), ('radioactive_decay', 'Radioactive Decay'), ('buoyancy', 'Buoyancy')], help_text='Selects which client-side simulation and template to render.', max_length=40),
        ),
    ]
