# Generated by Django 5.2.17 on 2026-09-20 08:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('physics', '0026_alter_physicssimulation_simulation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PhysicsScenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField(blank=True, max_length=220, unique=True)),
                ('description', models.TextField(blank=True, default='', help_text='Teacher-facing summary shown in the scenario list.')),
                ('instructions', models.TextField(help_text="The student-facing task, e.g. 'Make the cart stop.'")),
                ('prediction_prompt', models.TextField(blank=True, default='', help_text='Optional prompt shown before the student experiments.')),
                ('reflection_prompt', models.TextField(blank=True, default='', help_text='Optional prompt for the existing Explain step.')),
                ('initial_state', models.JSONField(blank=True, default=dict, help_text="Suggested starting values, keyed by the simulation's own input field names. Validated against that simulation's registered bounds -- never arbitrary fields.")),
                ('target_condition', models.JSONField(default=dict, help_text='A single structured goal -- kind/field/at_time_s/target/tolerance (or range_min/range_max), matching lab_scenarios.TargetCondition exactly. Never a formula or expression.')),
                ('difficulty', models.CharField(choices=[('foundation', 'Foundation'), ('introductory', 'Introductory'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], default='introductory', max_length=20)),
                ('category', models.CharField(blank=True, choices=[('investigation', 'Investigation'), ('challenge', 'Challenge'), ('prediction', 'Prediction'), ('measurement', 'Measurement'), ('comparison', 'Comparison')], default='', max_length=20)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('active', 'Active'), ('archived', 'Archived')], default='draft', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='physics_scenarios', to=settings.AUTH_USER_MODEL)),
                ('simulation', models.ForeignKey(help_text='The existing Physics Lab this scenario runs inside.', on_delete=django.db.models.deletion.PROTECT, related_name='teacher_scenarios', to='physics.physicssimulation')),
            ],
            options={
                'ordering': ['-updated_at', '-id'],
                'indexes': [models.Index(fields=['status', '-updated_at'], name='physics_phy_status_71f5fc_idx'), models.Index(fields=['created_by', 'status'], name='physics_phy_created_ca83ee_idx')],
            },
        ),
    ]
