# Generated by Django 5.2.17 on 2026-09-02 06:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lessons', '0003_alter_lesson_common_misconceptions_and_more'),
        ('physics', '0003_physicssimulation'),
        ('students', '0003_experimentattempt_learningevidence_context_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherIntervention',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('recommend_lesson', 'Recommend a lesson'), ('recommend_experiment', 'Recommend an experiment'), ('tutor_follow_up', 'Follow up with the Tutor'), ('teacher_note', 'Teacher note')], max_length=32)),
                ('note', models.TextField(blank=True, default='')),
                ('metadata', models.JSONField(blank=True, default=dict, help_text='Sanitised snapshot of the target ids for the audit trail.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('concept', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_interventions', to='physics.physicsconcept')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_interventions', to='lessons.lesson')),
                ('misconception', models.ForeignKey(blank=True, help_text='An optional possible-misconception this action responds to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_interventions', to='students.studentmisconception')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='teacher_interventions', to='students.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, help_text='The authenticated teacher who recorded this action.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_interventions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'created_at'], name='teachers_te_student_be30bd_idx')],
            },
        ),
    ]
