# Generated by Django 5.2.17 on 2026-09-02 07:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_common_misconceptions_and_more'),
        ('physics', '0003_physicssimulation'),
        ('students', '0003_experimentattempt_learningevidence_context_and_more'),
        ('teachers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherintervention',
            name='acted_at',
            field=models.DateTimeField(blank=True, help_text='When the student first acted on this recommendation.', null=True),
        ),
        migrations.AddField(
            model_name='teacherintervention',
            name='simulation',
            field=models.ForeignKey(blank=True, help_text='An optional Physics Lab simulation for an experiment recommendation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='teacher_interventions', to='physics.physicssimulation'),
        ),
        migrations.AddField(
            model_name='teacherintervention',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('opened', 'Opened'), ('completed', 'Completed'), ('dismissed', 'Dismissed')], default='pending', help_text='Recommendation lifecycle. Irrelevant for a teacher-only note.', max_length=16),
        ),
        migrations.AddIndex(
            model_name='teacherintervention',
            index=models.Index(fields=['student', 'action_type', 'status'], name='teachers_te_student_494756_idx'),
        ),
    ]
