# Generated by Django 5.2.17 on 2026-09-03 16:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0003_alter_lesson_common_misconceptions_and_more'),
        ('physics', '0003_physicssimulation'),
        ('students', '0004_practiceattempt'),
        ('teachers', '0002_teacherintervention_acted_at_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TeacherLearningGoal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('teacher_note', models.TextField(blank=True, default='', help_text='Private teacher reasoning. Never shown to the student.')),
                ('status', models.CharField(choices=[('active', 'Active'), ('completed', 'Completed'), ('closed', 'Closed')], default='active', help_text='Workflow state -- not a mastery signal.', max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, help_text='Set only when a real target-activity completion signal fired.', null=True)),
                ('closed_at', models.DateTimeField(blank=True, help_text='Set when a teacher explicitly closes the goal.', null=True)),
                ('concept', models.ForeignKey(help_text='The Physics concept the teacher wants the student to focus on.', on_delete=django.db.models.deletion.PROTECT, related_name='learning_goals', to='physics.physicsconcept')),
                ('lesson', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_goals', to='lessons.lesson')),
                ('misconception', models.ForeignKey(blank=True, help_text='An optional possible-misconception this goal responds to. Teacher-only.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_goals', to='students.studentmisconception')),
                ('simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_goals', to='physics.physicssimulation')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='learning_goals', to='students.studentprofile')),
                ('teacher', models.ForeignKey(blank=True, help_text='The authenticated teacher who set this goal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='learning_goals', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['student', 'status', '-created_at'], name='teachers_te_student_bab6dc_idx'), models.Index(fields=['student', '-created_at'], name='teachers_te_student_99fd9c_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('status', 'active')), fields=('student', 'concept', 'lesson', 'simulation'), name='uniq_active_learning_goal')],
            },
        ),
    ]
