"""Deterministic "what should this student do next" planner.

This is activity *selection*, not grading. It never diagnoses, never claims
mastery / readiness / weakness, never calls an AI provider, never writes a row
(no evidence, no intervention, no goal, no recommendation), and it always
resolves to an activity that already exists in the project (a lesson, a practice
page, a Physics Lab simulation, or the Tutor). The same database state always
yields the same plan; ``now`` is injectable so recency is testable.

It composes existing systems rather than duplicating them:

* an active :class:`TeacherLearningGoal` fixes the focus concept (Step 21);
* a pending / opened :class:`TeacherIntervention` recommendation is surfaced but
  never mutated (Step 17);
* the concept graph supplies a fallback focus (Step 20);
* ``build_student_learning_patterns`` supplies the ultimate fallback (Step 19).

Priority the primary activity is chosen with (documented + tested):

    1. Active teacher learning goal      -> the goal's own next activity
    2. Pending / opened recommendation   -> open the recommendations inbox
    3. An unfinished Physics Lab run     -> return and finish it
    4. An activity for the focus concept -> lesson / practice / lab / tutor
    5. Step 19 ``next_investigation``     -> generic fallback

The focus concept is resolved once, independently:
    teacher goal > pending recommendation > graph next-concept > most recent
    activity > none.
"""

from __future__ import annotations

from dataclasses import asdict, dataclass
from types import SimpleNamespace

from django.urls import reverse
from django.utils import timezone
from django.utils.http import urlencode

from apps.physics.concept_graph import build_physics_concept_graph
from apps.students.concept_path_services import (
    build_concept_destination_maps,
    build_student_concept_path,
)

from .models import ExperimentAttempt, PracticeAttempt, TutorMessage
from .pattern_services import build_student_learning_patterns
from .practice_services import get_practice_questions

PLAN_ALTERNATIVE_LIMIT = 2
_GRADEABLE_TYPES = {"numeric", "multiple_choice"}

PLANNER_NOTE = (
    "This suggestion is generated by a deterministic planner from your recorded "
    "activity. It is not a decision made by your teacher."
)


@dataclass(frozen=True)
class PlannedActivity:
    type: str  # lesson | practice | lab | tutor | recommendation | explore
    title: str
    description: str
    url: str
    cta: str
    target_label: str


def _as_dict(activity: PlannedActivity | None):
    return asdict(activity) if activity is not None else None


# --- data loading (kept apart from the decision logic) ------------------


def _load_context(student, now, patterns=None, graph=None):
    now = now or timezone.now()
    from apps.teachers.models import TeacherIntervention, TeacherLearningGoal

    if patterns is None:
        patterns = build_student_learning_patterns(student=student, now=now)
    if patterns.get("next_investigation") is None:
        # A shared patterns dict must still carry the Step 19 next-step so the
        # plan is identical whichever page asks for it. Callers that reuse
        # patterns are expected to build them with next_investigation; this
        # re-derives it defensively rather than silently degrading rule 5.
        patterns = {
            **patterns,
            "next_investigation": build_student_learning_patterns(
                student=student, now=now
            )["next_investigation"],
        }
    if graph is None:
        graph = build_physics_concept_graph()

    concept_path = build_student_concept_path(
        student=student, now=now, patterns=patterns, with_actions=False, graph=graph
    )
    lesson_by_slug, sim_by_slug = build_concept_destination_maps()

    goal = (
        TeacherLearningGoal.objects.filter(
            student=student, status=TeacherLearningGoal.Status.ACTIVE
        )
        .select_related("concept", "lesson", "simulation")
        .order_by("-created_at", "-id")
        .first()
    )
    recommendation = (
        TeacherIntervention.objects.filter(
            student=student,
            action_type__in=TeacherIntervention.STUDENT_VISIBLE_ACTIONS,
            status__in=[
                TeacherIntervention.Status.PENDING,
                TeacherIntervention.Status.OPENED,
            ],
        )
        .select_related("concept", "lesson", "simulation", "simulation__concept")
        .prefetch_related("lesson__physics_concepts")
        .order_by("-created_at", "-id")
        .first()
    )
    incomplete_experiment = (
        ExperimentAttempt.objects.filter(student=student, completed_at__isnull=True)
        .select_related("simulation", "simulation__concept")
        .order_by("-started_at", "-id")
        .first()
    )

    return SimpleNamespace(
        now=now,
        student=student,
        patterns=patterns,
        graph=graph,
        concept_path=concept_path,
        lesson_by_slug=lesson_by_slug,
        sim_by_slug=sim_by_slug,
        goal=goal,
        recommendation=recommendation,
        incomplete_experiment=incomplete_experiment,
        activity_by_concept={
            row["concept"]: row for row in patterns.get("concept_activity", [])
        },
        _engaged={},
        _practice_done={},
        _experiment_done={},
        _gradeable={},
    )


# --- small factual signal helpers (memoised, one bounded query each) ----


def _engaged_with_lesson(ctx, lesson_id) -> bool:
    """The student has concretely worked on this lesson -- a practice attempt or
    a message to the Tutor in one of its sessions."""

    if lesson_id not in ctx._engaged:
        ctx._engaged[lesson_id] = (
            PracticeAttempt.objects.filter(
                student=ctx.student, lesson_id=lesson_id
            ).exists()
            or TutorMessage.objects.filter(
                session__student=ctx.student,
                session__lesson_id=lesson_id,
                role=TutorMessage.Role.STUDENT,
            ).exists()
        )
    return ctx._engaged[lesson_id]


def _practice_fully_attempted(ctx, lesson) -> bool:
    if lesson.pk not in ctx._practice_done:
        keys = {
            q.key for q in get_practice_questions(lesson) if q.type in _GRADEABLE_TYPES
        }
        if not keys:
            ctx._practice_done[lesson.pk] = False
        else:
            # A lesson has at most a few dozen distinct question keys; the cap
            # only guards against a pathological retry history.
            attempted = set(
                PracticeAttempt.objects.filter(
                    student=ctx.student, lesson_id=lesson.pk
                ).values_list("question_key", flat=True)[:2000]
            )
            ctx._practice_done[lesson.pk] = keys.issubset(attempted)
    return ctx._practice_done[lesson.pk]


def _has_gradeable_practice(ctx, lesson) -> bool:
    if lesson.pk not in ctx._gradeable:
        ctx._gradeable[lesson.pk] = any(
            q.type in _GRADEABLE_TYPES for q in get_practice_questions(lesson)
        )
    return ctx._gradeable[lesson.pk]


def _experiment_completed(ctx, simulation_id) -> bool:
    if simulation_id not in ctx._experiment_done:
        ctx._experiment_done[simulation_id] = ExperimentAttempt.objects.filter(
            student=ctx.student,
            simulation_id=simulation_id,
            completed_at__isnull=False,
        ).exists()
    return ctx._experiment_done[simulation_id]


def _tutor_discussed(ctx, concept_name) -> bool:
    row = ctx.activity_by_concept.get(concept_name)
    return bool(row and row.get("tutor", {}).get("student_messages", 0) > 0)


def _concept_of(obj):
    """Best concept for a recommendation / experiment: direct, else a lesson's
    sole concept, else the simulation's concept."""

    if getattr(obj, "concept_id", None):
        return obj.concept
    lesson = getattr(obj, "lesson", None)
    if lesson is not None:
        concepts = list(lesson.physics_concepts.all())
        if len(concepts) == 1:
            return concepts[0]
    simulation = getattr(obj, "simulation", None)
    if simulation is not None:
        return simulation.concept
    return None


# --- activity builders (controlled human text only) --------------------


def _lesson_activity(lesson, concept_name) -> PlannedActivity:
    return PlannedActivity(
        type="lesson",
        title=f"Review the {lesson.title} lesson",
        description=f"Open the lesson that teaches {concept_name} and work through it.",
        url=reverse("students:tutor", args=[lesson.slug]),
        cta="Open Lesson",
        target_label=f"Lesson: {lesson.title}",
    )


def _practice_activity(lesson, concept_name) -> PlannedActivity:
    return PlannedActivity(
        type="practice",
        title=f"Try a practice problem on {concept_name}",
        description=f"Answer the practice questions in {lesson.title}.",
        url=reverse("students:practice", args=[lesson.slug]),
        cta="Open Practice",
        target_label=f"Practice: {lesson.title}",
    )


def _lab_activity(simulation, concept_name) -> PlannedActivity:
    return PlannedActivity(
        type="lab",
        title=f"Investigate {concept_name} in the Physics Lab",
        description=f"Run the {simulation.title} simulation and record what happens.",
        url=reverse("physics_lab:detail", args=[simulation.slug]),
        cta="Open Physics Lab",
        target_label=f"Physics Lab: {simulation.title}",
    )


def _tutor_activity(lesson, concept_name) -> PlannedActivity:
    prefill = f"I want to understand {concept_name}. Can you help me get started?"
    return PlannedActivity(
        type="tutor",
        title=f"Discuss {concept_name} with the Physics Tutor",
        description="Ask the Tutor a question and reason through it together.",
        url=reverse("students:tutor", args=[lesson.slug]) + "?" + urlencode({"prefill": prefill}),
        cta="Ask the Tutor",
        target_label=f"Tutor: {lesson.title}",
    )


def _concept_activity_options(ctx, concept_name, concept_slug):
    """Every existing activity for a concept, in resolution order, each tagged
    with whether the student has already done it."""

    options: list[tuple[PlannedActivity, bool]] = []
    lesson = ctx.lesson_by_slug.get(concept_slug)
    simulation = ctx.sim_by_slug.get(concept_slug)

    if lesson is not None:
        options.append((_lesson_activity(lesson, concept_name), _engaged_with_lesson(ctx, lesson.pk)))
        if _has_gradeable_practice(ctx, lesson):
            options.append(
                (_practice_activity(lesson, concept_name), _practice_fully_attempted(ctx, lesson))
            )
    if simulation is not None:
        options.append(
            (_lab_activity(simulation, concept_name), _experiment_completed(ctx, simulation.pk))
        )
    if lesson is not None:
        options.append((_tutor_activity(lesson, concept_name), _tutor_discussed(ctx, concept_name)))
    return options


def _pick(options) -> PlannedActivity | None:
    for activity, done in options:
        if not done:
            return activity
    # Everything the concept offers is already done. The Tutor is always a
    # useful next step (there is more to discuss); otherwise return None so the
    # caller can fall through rather than re-suggesting finished work.
    for activity, _done in options:
        if activity.type == "tutor":
            return activity
    return None


# --- focus + primary + alternatives -----------------------------------


def _resolve_focus(ctx) -> dict:
    if ctx.goal is not None:
        return {"concept": ctx.goal.concept.name, "source": "teacher_goal"}
    if ctx.recommendation is not None:
        concept = _concept_of(ctx.recommendation)
        return {"concept": concept.name if concept else "", "source": "pending_recommendation"}
    candidates = ctx.concept_path.get("next_candidates") or []
    if candidates:
        return {"concept": candidates[0]["name"], "source": "learning_path"}
    concept_activity = ctx.patterns.get("concept_activity") or []
    if concept_activity:
        return {"concept": concept_activity[0]["concept"], "source": "recent_activity"}
    return {"concept": "", "source": ""}


def _goal_activity(ctx, goal, focus_slug) -> PlannedActivity | None:
    concept_name = goal.concept.name

    if goal.simulation_id and not _experiment_completed(ctx, goal.simulation_id):
        return _lab_activity(goal.simulation, concept_name)

    if goal.lesson_id:
        lesson = goal.lesson
        if not _engaged_with_lesson(ctx, lesson.pk):
            return _lesson_activity(lesson, concept_name)
        if _has_gradeable_practice(ctx, lesson) and not _practice_fully_attempted(ctx, lesson):
            return _practice_activity(lesson, concept_name)
        # lesson engaged and its practice done / absent -> fall through to
        # whatever else the concept offers (a lab, the Tutor).

    if focus_slug:
        picked = _pick(_concept_activity_options(ctx, concept_name, focus_slug))
        if picked is not None:
            return picked

    return PlannedActivity(
        type="explore",
        title=f"Explore {concept_name}",
        description="Choose a Physics activity related to this concept.",
        url=reverse("students:lessons"),
        cta="Browse Lessons",
        target_label=concept_name,
    )


def _goal_reason(activity_type: str) -> str:
    if activity_type == "lesson":
        return "Your teacher selected this concept -- start with its lesson."
    if activity_type == "practice":
        return "You have started this lesson; its practice questions are the next step for your goal."
    if activity_type == "lab":
        return "The Physics Lab is the activity your teacher selected for this goal."
    if activity_type == "tutor":
        return "You have worked through this goal's lesson and practice -- talking it through is a good next step."
    return "This activity matches your teacher-selected learning goal."


def _focus_reason(source: str) -> str:
    if source == "learning_path":
        return "This continues the concept path from Physics you have already investigated."
    if source == "recent_activity":
        return "This connects to the Physics concepts you have recently explored."
    return "This continues from the Physics activities you have recently worked through."


def _resolve_primary(ctx, focus, focus_slug):
    if ctx.goal is not None:
        activity = _goal_activity(ctx, ctx.goal, focus_slug)
        if activity is not None:
            return activity, _goal_reason(activity.type)

    if ctx.goal is None and ctx.recommendation is not None:
        return (
            PlannedActivity(
                type="recommendation",
                title="Open your teacher's recommendation",
                description="Your teacher has a recommendation waiting. Open it from your recommendations inbox.",
                url=reverse("students:recommendations"),
                cta="Open Recommendations",
                target_label="",
            ),
            "Your teacher recommended a next step for you to open.",
        )

    if ctx.goal is None and ctx.recommendation is None and ctx.incomplete_experiment is not None:
        simulation = ctx.incomplete_experiment.simulation
        return (
            PlannedActivity(
                type="lab",
                title="Finish your Physics Lab experiment",
                description="You started an experiment but have not recorded your explanation yet.",
                url=reverse("physics_lab:detail", args=[simulation.slug]),
                cta="Return to the Physics Lab",
                target_label=f"Physics Lab: {simulation.title}",
            ),
            "You have a Physics Lab experiment that is not finished yet.",
        )

    if focus["concept"] and focus_slug:
        picked = _pick(_concept_activity_options(ctx, focus["concept"], focus_slug))
        if picked is not None:
            return picked, _focus_reason(focus["source"])

    next_investigation = ctx.patterns.get("next_investigation")
    if next_investigation:
        return (
            PlannedActivity(
                type="explore",
                title=next_investigation["text"],
                description="",
                url=next_investigation["url"],
                cta=f"Go to {next_investigation['url_label']}",
                target_label="",
            ),
            "This continues from the Physics activities you have recently worked through.",
        )

    return None, "There isn't a Physics activity to suggest yet. Open a lesson or the Physics Lab to get started."


def _resolve_alternatives(ctx, focus, focus_slug, primary):
    """Up to two other, not-yet-done activities for the same focus concept."""

    if primary is None or not (focus["concept"] and focus_slug):
        return []
    seen = {primary.type}
    alternatives: list[PlannedActivity] = []
    for activity, done in _concept_activity_options(ctx, focus["concept"], focus_slug):
        if done or activity.type in seen:
            continue
        seen.add(activity.type)
        alternatives.append(activity)
        if len(alternatives) >= PLAN_ALTERNATIVE_LIMIT:
            break
    return alternatives


# --- public API -----------------------------------------------------


def build_adaptive_activity_plan(*, student, now=None, patterns=None, graph=None) -> dict:
    """One deterministic next activity for ``student`` plus up to two alternatives."""

    ctx = _load_context(student, now, patterns=patterns, graph=graph)
    focus = _resolve_focus(ctx)
    focus_slug = ctx.graph.slug_for_name(focus["concept"]) if focus["concept"] else None

    primary, reason = _resolve_primary(ctx, focus, focus_slug)
    alternatives = _resolve_alternatives(ctx, focus, focus_slug, primary)

    teacher_goal = None
    if ctx.goal is not None:
        teacher_goal = {
            "concept": ctx.goal.concept.name,
            "target_label": ctx.goal.target_label,
        }

    return {
        "has_plan": primary is not None,
        "focus": focus if (focus["concept"] or focus["source"]) else None,
        "teacher_goal": teacher_goal,
        "next_activity": _as_dict(primary),
        "reason": reason,
        "alternatives": [_as_dict(a) for a in alternatives],
        "planner_note": PLANNER_NOTE,
    }
