"""Teacher Scenario Studio: teacher-authored Physics Lab investigations.

Covers the ``PhysicsScenario`` model, its validation/service layer
(``scenario_services.py``), its conversion into the existing deterministic
checker (``lab_scenarios.py``), the teacher-facing CRUD views, the student
launch/check flow, Teacher Evidence, Lesson integration, and AI-assisted
drafting -- all reusing the existing Physics Lab, evidence and AI
architecture rather than a second engine.
"""

from __future__ import annotations

import json

from django.contrib.auth import get_user_model
from django.contrib.auth.models import AnonymousUser
from django.test import Client, TestCase, override_settings
from django.urls import reverse

from apps.ai.providers import FakeAIProvider
from apps.physics import scenario_services as services
from apps.physics.lab_scenarios import (
    TEACHER_SCENARIO_PREFIX,
    allowed_target_kinds,
    evaluate_scenario,
    get_scenario,
    scenarios_for,
    to_lab_scenario,
    value_fields_for,
)
from apps.physics.models import PhysicsConcept, PhysicsScenario, PhysicsSimulation
from apps.students.models import ExperimentAttempt, LearningEvidence, StudentProfile

User = get_user_model()
PW = "pw12345"


def _kinematics_sim(*, title="Kinematics -- Straight-Line Motion", is_active=True):
    # PhysicsConcept.name/slug are both unique, so a test that builds two
    # Kinematics simulations (e.g. one active, one not) must share one
    # concept rather than create a second row with the same name.
    concept, _ = PhysicsConcept.objects.get_or_create(
        name="Kinematics", defaults={"description": "Straight-line motion.", "topic": "Kinematics"}
    )
    return PhysicsSimulation.objects.create(
        concept=concept,
        title=title,
        simulation_type=PhysicsSimulation.SimulationType.KINEMATICS,
        is_active=is_active,
    )


def _newtons_second_law_sim(*, title="Newton's Second Law Lab"):
    concept, _ = PhysicsConcept.objects.get_or_create(
        name="Force", defaults={"description": "A push or pull.", "topic": "Dynamics"}
    )
    return PhysicsSimulation.objects.create(
        concept=concept, title=title,
        simulation_type=PhysicsSimulation.SimulationType.NEWTONS_SECOND_LAW,
    )


def _projectile_sim():
    # Registered (so get_simulation_definition finds it) but not yet a
    # Scenario Studio-supported type -- the negative example for "this
    # simulation type is not scoped in yet", now that both Kinematics and
    # Newton's Second Law are supported.
    concept = PhysicsConcept.objects.create(
        name="Projectile Motion", description="2D motion under gravity.", topic="Kinematics"
    )
    return PhysicsSimulation.objects.create(
        concept=concept, title="Projectile Motion Lab",
        simulation_type=PhysicsSimulation.SimulationType.PROJECTILE_MOTION,
    )


_STOP_TARGET = {
    "kind": "value", "field": "velocity_m_s", "at_time_s": 5,
    "target": 0, "tolerance": 0.1,
}


class PhysicsScenarioModelTests(TestCase):
    def setUp(self):
        self.sim = _kinematics_sim()
        self.teacher = User.objects.create_user("teach", password=PW, is_staff=True)

    def _create(self, **overrides):
        fields = dict(
            title="Make the cart stop",
            simulation=self.sim,
            instructions="Bring the cart to rest at t = 5 s.",
            initial_state={"initial_velocity_m_s": 10, "acceleration_m_s2": -2},
            target_condition=dict(_STOP_TARGET, description="velocity is 0 at t=5s"),
            created_by=self.teacher,
        )
        fields.update(overrides)
        return PhysicsScenario.objects.create(**fields)

    def test_creation_and_defaults(self):
        scenario = self._create()
        self.assertEqual(scenario.status, PhysicsScenario.Status.DRAFT)
        self.assertEqual(scenario.difficulty, PhysicsScenario.Difficulty.INTRODUCTORY)
        self.assertEqual(scenario.category, "")
        self.assertFalse(scenario.is_active)

    def test_slug_autogenerated_and_unique(self):
        first = self._create(title="Reach the mark")
        second = self._create(title="Reach the mark")
        self.assertEqual(first.slug, "reach-the-mark")
        self.assertNotEqual(first.slug, second.slug)
        self.assertTrue(second.slug.startswith("reach-the-mark"))

    def test_str_returns_title(self):
        self.assertEqual(str(self._create(title="Hit the mark")), "Hit the mark")

    def test_is_active_property_tracks_status(self):
        scenario = self._create(status=PhysicsScenario.Status.ACTIVE)
        self.assertTrue(scenario.is_active)

    def test_simulation_is_protected_on_delete(self):
        self._create()
        from django.db.models import ProtectedError

        with self.assertRaises(ProtectedError):
            self.sim.delete()

    def test_created_by_set_null_on_user_delete(self):
        scenario = self._create()
        self.teacher.delete()
        scenario.refresh_from_db()
        self.assertIsNone(scenario.created_by_id)


class ScenarioValidationTests(TestCase):
    """The allow-list validators in ``scenario_services.py`` -- the only path
    by which a scenario's Physics identity is ever set, whether typed by a
    teacher or suggested by the AI."""

    def setUp(self):
        self.sim = _kinematics_sim()

    def test_valid_initial_state_is_accepted(self):
        cleaned = services._validate_initial_state(
            "kinematics", {"initial_velocity_m_s": "10", "acceleration_m_s2": "-2"}
        )
        self.assertEqual(cleaned, {"initial_velocity_m_s": 10.0, "acceleration_m_s2": -2.0})

    def test_unknown_initial_state_field_is_silently_dropped_not_stored(self):
        cleaned = services._validate_initial_state(
            "kinematics", {"initial_velocity_m_s": "5", "warp_factor": "9"}
        )
        self.assertNotIn("warp_factor", cleaned)

    def test_out_of_range_initial_state_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services._validate_initial_state("kinematics", {"acceleration_m_s2": "999"})

    def test_nan_and_infinity_are_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services._validate_initial_state("kinematics", {"initial_velocity_m_s": "nan"})
        with self.assertRaises(services.ScenarioError):
            services._validate_initial_state("kinematics", {"initial_velocity_m_s": "inf"})

    def test_non_numeric_initial_state_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services._validate_initial_state(
                "kinematics", {"initial_velocity_m_s": "<script>alert(1)</script>"}
            )

    def test_unknown_target_kind_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services._validate_target_condition(
                "kinematics", {"kind": "does_not_exist", "field": "velocity_m_s", "target": 0}
            )

    def test_invalid_target_field_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services._validate_target_condition(
                "kinematics", {"kind": "value", "field": "warp_factor", "target": 0, "tolerance": 1}
            )

    def test_negative_tolerance_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services._validate_target_condition(
                "kinematics",
                {"kind": "value", "field": "velocity_m_s", "target": 0, "tolerance": -1},
            )

    def test_within_range_min_greater_than_max_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services._validate_target_condition(
                "kinematics",
                {"kind": "within_range", "field": "position_m", "range_min": 10, "range_max": 1},
            )

    def test_target_time_out_of_bounds_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services._validate_target_condition(
                "kinematics",
                {"kind": "value", "field": "velocity_m_s", "target": 0, "tolerance": 1, "at_time_s": 999},
            )

    def test_valid_target_condition_round_trips_through_real_dataclass(self):
        cleaned = services._validate_target_condition("kinematics", _STOP_TARGET)
        self.assertEqual(cleaned["kind"], "value")
        self.assertIn("description", cleaned)

    def test_nonexistent_simulation_id_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services._resolve_simulation(999999)

    def test_non_numeric_simulation_id_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services._resolve_simulation("not-a-number")

    def test_inactive_simulation_is_rejected(self):
        inactive = _kinematics_sim(title="Inactive Kinematics", is_active=False)
        with self.assertRaises(services.ScenarioError):
            services._resolve_simulation(inactive.pk)

    def test_unsupported_simulation_type_is_rejected(self):
        projectile = _projectile_sim()
        with self.assertRaises(services.ScenarioError):
            services._resolve_simulation(projectile.pk)

    def test_newtons_second_law_simulation_is_supported(self):
        n2l = _newtons_second_law_sim()
        resolved = services._resolve_simulation(n2l.pk)
        self.assertEqual(resolved.pk, n2l.pk)


class ScenarioServiceCrudTests(TestCase):
    def setUp(self):
        self.sim = _kinematics_sim()
        self.teacher = User.objects.create_user("teach", password=PW, is_staff=True)
        self.other = User.objects.create_user("other_teach", password=PW, is_staff=True)

    def _create(self, teacher=None):
        return services.create_scenario(
            teacher=teacher or self.teacher,
            title="Make the cart stop",
            simulation_id=self.sim.pk,
            instructions="Bring the cart to rest at t = 5 s.",
            initial_state={"initial_velocity_m_s": 10, "acceleration_m_s2": -2},
            target_condition=_STOP_TARGET,
        )

    def test_create_sets_owner_and_slug_and_locked_fields(self):
        scenario = self._create()
        self.assertEqual(scenario.created_by_id, self.teacher.id)
        self.assertTrue(scenario.slug)
        self.assertEqual(scenario.status, PhysicsScenario.Status.DRAFT)
        self.assertEqual(scenario.initial_state["initial_velocity_m_s"], 10.0)

    def test_create_with_unauthenticated_user_records_no_owner(self):
        scenario = services.create_scenario(
            teacher=AnonymousUser(),
            title="Anon draft",
            simulation_id=self.sim.pk,
            instructions="x",
            initial_state={},
            target_condition=_STOP_TARGET,
        )
        self.assertIsNone(scenario.created_by_id)

    def test_missing_title_or_instructions_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services.create_scenario(
                teacher=self.teacher, title="", simulation_id=self.sim.pk,
                instructions="x", target_condition=_STOP_TARGET,
            )
        with self.assertRaises(services.ScenarioError):
            services.create_scenario(
                teacher=self.teacher, title="Title", simulation_id=self.sim.pk,
                instructions="", target_condition=_STOP_TARGET,
            )

    def test_update_by_non_owner_raises_permission_error(self):
        scenario = self._create()
        with self.assertRaises(services.ScenarioPermissionError):
            services.update_scenario(scenario_id=scenario.pk, teacher=self.other, title="Hijacked")
        scenario.refresh_from_db()
        self.assertNotEqual(scenario.title, "Hijacked")

    def test_update_presentation_fields_by_owner_succeeds(self):
        scenario = self._create()
        updated = services.update_scenario(
            scenario_id=scenario.pk, teacher=self.teacher, title="Renamed", difficulty="advanced",
        )
        self.assertEqual(updated.title, "Renamed")
        self.assertEqual(updated.difficulty, "advanced")

    def test_physics_fields_lock_after_first_student_check(self):
        scenario = self._create()
        services.set_scenario_status(
            scenario_id=scenario.pk, teacher=self.teacher, status=PhysicsScenario.Status.ACTIVE
        )
        scenario.refresh_from_db()
        student = StudentProfile.objects.create(display_name="Alex")
        services.record_scenario_check(student=student, scenario=scenario, met=True, checks=[])

        self.assertTrue(services.is_used(scenario))
        with self.assertRaises(services.ScenarioError):
            services.update_scenario(
                scenario_id=scenario.pk, teacher=self.teacher,
                initial_state={"initial_velocity_m_s": 999},
            )
        with self.assertRaises(services.ScenarioError):
            services.update_scenario(
                scenario_id=scenario.pk, teacher=self.teacher, target_condition=_STOP_TARGET,
            )
        with self.assertRaises(services.ScenarioError):
            services.update_scenario(
                scenario_id=scenario.pk, teacher=self.teacher, simulation_id=self.sim.pk,
            )
        # presentation fields remain editable once locked
        updated = services.update_scenario(
            scenario_id=scenario.pk, teacher=self.teacher, title="Still editable"
        )
        self.assertEqual(updated.title, "Still editable")
        self.assertEqual(updated.initial_state["initial_velocity_m_s"], 10.0)

    def test_set_status_by_non_owner_raises(self):
        scenario = self._create()
        with self.assertRaises(services.ScenarioPermissionError):
            services.set_scenario_status(
                scenario_id=scenario.pk, teacher=self.other, status=PhysicsScenario.Status.ACTIVE
            )

    def test_delete_blocked_once_used(self):
        scenario = self._create()
        student = StudentProfile.objects.create(display_name="Alex")
        services.record_scenario_check(student=student, scenario=scenario, met=True, checks=[])
        with self.assertRaises(services.ScenarioError):
            services.delete_scenario(scenario_id=scenario.pk, teacher=self.teacher)
        self.assertTrue(PhysicsScenario.objects.filter(pk=scenario.pk).exists())

    def test_delete_blocked_when_linked_to_a_lesson_activity(self):
        from apps.lessons.authoring_services import create_activity
        from apps.lessons.models import Lesson

        scenario = self._create()
        services.set_scenario_status(
            scenario_id=scenario.pk, teacher=self.teacher, status=PhysicsScenario.Status.ACTIVE
        )
        lesson = Lesson.objects.create(
            title="L", topic="Kinematics", grade_level="11",
            duration_minutes=45, learning_objectives=["x"],
        )
        create_activity(
            lesson=lesson, teacher=self.teacher, activity_type="scenario",
            title="Try it", reference_id=scenario.pk,
        )
        with self.assertRaises(services.ScenarioError):
            services.delete_scenario(scenario_id=scenario.pk, teacher=self.teacher)

    def test_delete_succeeds_when_unused_and_unlinked(self):
        scenario = self._create()
        services.delete_scenario(scenario_id=scenario.pk, teacher=self.teacher)
        self.assertFalse(PhysicsScenario.objects.filter(pk=scenario.pk).exists())

    def test_list_teacher_scenarios_filters_by_owner(self):
        mine = self._create()
        self._create(teacher=self.other)
        result = list(services.list_teacher_scenarios(teacher=self.teacher))
        self.assertEqual(result, [mine])

    def test_legacy_scenario_with_no_owner_is_editable_by_any_teacher(self):
        scenario = self._create()
        scenario.created_by = None
        scenario.save(update_fields=["created_by"])
        updated = services.update_scenario(scenario_id=scenario.pk, teacher=self.other, title="Adopted")
        self.assertEqual(updated.title, "Adopted")


class ScenarioCheckerIntegrationTests(TestCase):
    """Confirms a ``PhysicsScenario`` row becomes the exact same
    ``LabScenario`` shape the two built-in challenges use, and that
    ``evaluate_scenario`` needs no changes to grade it."""

    def setUp(self):
        self.sim = _kinematics_sim()
        self.teacher = User.objects.create_user("teach", password=PW, is_staff=True)

    def _active_scenario(self, *, initial_state, target_condition, title="Stop the cart"):
        scenario = services.create_scenario(
            teacher=self.teacher, title=title, simulation_id=self.sim.pk,
            instructions="x", initial_state=initial_state, target_condition=target_condition,
        )
        services.set_scenario_status(
            scenario_id=scenario.pk, teacher=self.teacher, status=PhysicsScenario.Status.ACTIVE
        )
        scenario.refresh_from_db()
        return scenario

    def test_to_lab_scenario_conversion_matches_shape(self):
        scenario = self._active_scenario(
            initial_state={"initial_velocity_m_s": 10, "acceleration_m_s2": -2},
            target_condition=_STOP_TARGET,
        )
        lab_scenario = to_lab_scenario(scenario)
        self.assertEqual(lab_scenario.scenario_id, f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}")
        self.assertEqual(lab_scenario.simulation_type, "kinematics")
        self.assertEqual(len(lab_scenario.targets), 1)

    def test_get_scenario_returns_none_for_draft(self):
        scenario = services.create_scenario(
            teacher=self.teacher, title="Draft one", simulation_id=self.sim.pk,
            instructions="x", target_condition=_STOP_TARGET,
        )
        self.assertIsNone(get_scenario(f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}"))

    def test_get_scenario_returns_none_when_simulation_goes_inactive(self):
        scenario = self._active_scenario(
            initial_state={}, target_condition=_STOP_TARGET,
        )
        self.sim.is_active = False
        self.sim.save(update_fields=["is_active"])
        self.assertIsNone(get_scenario(f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}"))

    def test_get_scenario_returns_active_teacher_scenario(self):
        scenario = self._active_scenario(initial_state={}, target_condition=_STOP_TARGET)
        found = get_scenario(f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}")
        self.assertIsNotNone(found)
        self.assertEqual(found.title, scenario.title)

    def test_scenarios_for_merges_builtin_and_teacher_scenarios(self):
        self._active_scenario(initial_state={}, target_condition=_STOP_TARGET, title="Teacher one")
        ids = {s.scenario_id for s in scenarios_for("kinematics")}
        self.assertIn("reach-20-at-4", ids)  # built-in, unchanged
        self.assertTrue(any(sid.startswith(TEACHER_SCENARIO_PREFIX) for sid in ids))

    def test_evaluate_scenario_stop_the_cart_manual_example(self):
        # Manual verification example: x0=0, v0=10, a=-2 -> v(5)=0.
        scenario = self._active_scenario(
            initial_state={"initial_velocity_m_s": 10, "acceleration_m_s2": -2},
            target_condition=_STOP_TARGET,
        )
        lab_scenario = get_scenario(f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}")
        result = evaluate_scenario(
            lab_scenario,
            parameters={"initial_position_m": 0, "initial_velocity_m_s": 10, "acceleration_m_s2": -2},
        )
        self.assertTrue(result["met"])

    def test_evaluate_scenario_position_within_range_manual_example(self):
        # Manual verification example: x0=0, v0=2, a=1 -> x(5) = 2*5 + 0.5*1*25 = 22.5.
        target = {
            "kind": "within_range", "field": "position_m", "at_time_s": 5,
            "range_min": 20, "range_max": 25,
        }
        scenario = self._active_scenario(
            initial_state={"initial_velocity_m_s": 2, "acceleration_m_s2": 1},
            target_condition=target, title="Reach the range",
        )
        lab_scenario = get_scenario(f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}")
        result = evaluate_scenario(
            lab_scenario,
            parameters={"initial_position_m": 0, "initial_velocity_m_s": 2, "acceleration_m_s2": 1},
        )
        self.assertTrue(result["met"])
        self.assertAlmostEqual(
            float(result["checks"][0]["detail"].split("was ")[1].split(";")[0]), 22.5, places=1
        )

    def test_evaluate_scenario_greater_than_and_less_than(self):
        gt = self._active_scenario(
            initial_state={"initial_velocity_m_s": 5, "acceleration_m_s2": 1},
            target_condition={"kind": "greater_than", "field": "velocity_m_s", "at_time_s": 2, "target": 5},
            title="Speed up",
        )
        lt = self._active_scenario(
            initial_state={"initial_velocity_m_s": 5, "acceleration_m_s2": -1},
            target_condition={"kind": "less_than", "field": "velocity_m_s", "at_time_s": 2, "target": 5},
            title="Slow down",
        )
        gt_scenario = get_scenario(f"{TEACHER_SCENARIO_PREFIX}{gt.slug}")
        lt_scenario = get_scenario(f"{TEACHER_SCENARIO_PREFIX}{lt.slug}")
        self.assertTrue(
            evaluate_scenario(
                gt_scenario,
                parameters={"initial_position_m": 0, "initial_velocity_m_s": 5, "acceleration_m_s2": 1},
            )["met"]
        )
        self.assertTrue(
            evaluate_scenario(
                lt_scenario,
                parameters={"initial_position_m": 0, "initial_velocity_m_s": 5, "acceleration_m_s2": -1},
            )["met"]
        )

    def test_forged_huge_values_are_clamped_and_cannot_cheat(self):
        scenario = self._active_scenario(
            initial_state={"initial_velocity_m_s": 10, "acceleration_m_s2": -2},
            target_condition=_STOP_TARGET,
        )
        lab_scenario = get_scenario(f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}")
        result = evaluate_scenario(
            lab_scenario,
            parameters={"initial_position_m": 9e9, "initial_velocity_m_s": 9e9, "acceleration_m_s2": 9e9},
        )
        self.assertFalse(result["met"])

    def test_built_in_scenarios_are_unaffected_regression(self):
        s = get_scenario("reach-20-at-4")
        self.assertTrue(
            evaluate_scenario(
                s,
                parameters={"initial_position_m": 0, "initial_velocity_m_s": 3, "acceleration_m_s2": 1},
            )["met"]
        )


class NewtonsSecondLawScenarioTests(TestCase):
    """The second Scenario Studio simulation type. Newton's Second Law has no
    free "initial velocity" -- the object always starts from rest, so under
    the constant acceleration a = F/m, v = a*t and x = 1/2 * a * t^2."""

    def setUp(self):
        self.sim = _newtons_second_law_sim()
        self.teacher = User.objects.create_user("teach", password=PW, is_staff=True)

    def _active_scenario(self, *, initial_state, target_condition, title="N2L scenario"):
        scenario = services.create_scenario(
            teacher=self.teacher, title=title, simulation_id=self.sim.pk,
            instructions="x", initial_state=initial_state, target_condition=target_condition,
        )
        services.set_scenario_status(
            scenario_id=scenario.pk, teacher=self.teacher, status=PhysicsScenario.Status.ACTIVE
        )
        scenario.refresh_from_db()
        return scenario

    def test_simulation_is_supported(self):
        resolved = services._resolve_simulation(self.sim.pk)
        self.assertEqual(resolved.pk, self.sim.pk)

    def test_value_fields_exclude_mass_and_force(self):
        fields = value_fields_for("newtons_second_law")
        self.assertEqual(fields, {"acceleration_m_s2", "velocity_m_s", "position_m"})

    def test_reverses_kind_is_not_offered_for_newtons_second_law(self):
        self.assertNotIn("reverses", allowed_target_kinds("newtons_second_law"))
        self.assertIn("reverses", allowed_target_kinds("kinematics"))

    def test_reverses_target_is_rejected_for_newtons_second_law(self):
        with self.assertRaises(services.ScenarioError):
            services._validate_target_condition("newtons_second_law", {"kind": "reverses"})

    def test_acceleration_target_manual_example(self):
        # mass = 2 kg, force = 10 N -> a = 5 m/s^2, constant regardless of time.
        scenario = self._active_scenario(
            initial_state={"mass_kg": 2, "force_n": 10},
            target_condition={
                "kind": "value", "field": "acceleration_m_s2", "at_time_s": 0,
                "target": 5, "tolerance": 0.1,
            },
        )
        lab_scenario = get_scenario(f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}")
        result = evaluate_scenario(lab_scenario, parameters={"mass_kg": 2, "force_n": 10})
        self.assertTrue(result["met"])

    def test_velocity_at_time_target_manual_example(self):
        # mass = 2 kg, force = 10 N -> a = 5 m/s^2 -> v(2) = 10 m/s.
        scenario = self._active_scenario(
            initial_state={"mass_kg": 2, "force_n": 10},
            target_condition={
                "kind": "value", "field": "velocity_m_s", "at_time_s": 2,
                "target": 10, "tolerance": 0.1,
            },
        )
        lab_scenario = get_scenario(f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}")
        result = evaluate_scenario(lab_scenario, parameters={"mass_kg": 2, "force_n": 10})
        self.assertTrue(result["met"])

    def test_position_at_time_target_manual_example(self):
        # mass = 2 kg, force = 10 N -> a = 5 m/s^2 -> x(2) = 0.5*5*4 = 10 m.
        scenario = self._active_scenario(
            initial_state={"mass_kg": 2, "force_n": 10},
            target_condition={
                "kind": "within_range", "field": "position_m", "at_time_s": 2,
                "range_min": 9, "range_max": 11,
            },
        )
        lab_scenario = get_scenario(f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}")
        result = evaluate_scenario(lab_scenario, parameters={"mass_kg": 2, "force_n": 10})
        self.assertTrue(result["met"])

    def test_forged_zero_mass_is_rejected_not_a_server_error(self):
        scenario = self._active_scenario(
            initial_state={"mass_kg": 2, "force_n": 10},
            target_condition={
                "kind": "value", "field": "acceleration_m_s2", "at_time_s": 0,
                "target": 5, "tolerance": 0.1,
            },
        )
        url = reverse(
            "physics_lab:experiment_scenario_check",
            args=[self.sim.slug, f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}"],
        )
        response = self.client.post(url, {"mass_kg": "0", "force_n": "10"})
        self.assertEqual(response.status_code, 400)

    def test_end_to_end_check_endpoint(self):
        scenario = self._active_scenario(
            initial_state={"mass_kg": 2, "force_n": 10},
            target_condition={
                "kind": "value", "field": "velocity_m_s", "at_time_s": 2,
                "target": 10, "tolerance": 0.5,
            },
        )
        url = reverse(
            "physics_lab:experiment_scenario_check",
            args=[self.sim.slug, f"{TEACHER_SCENARIO_PREFIX}{scenario.slug}"],
        )
        response = self.client.post(url, {"mass_kg": "2", "force_n": "10"})
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.json()["met"])

    def test_scenario_appears_in_scenarios_for_and_lab_page(self):
        self._active_scenario(
            initial_state={"mass_kg": 2, "force_n": 10},
            target_condition={
                "kind": "value", "field": "acceleration_m_s2", "at_time_s": 0,
                "target": 5, "tolerance": 0.1,
            },
        )
        ids = {s.scenario_id for s in scenarios_for("newtons_second_law")}
        self.assertTrue(any(sid.startswith(TEACHER_SCENARIO_PREFIX) for sid in ids))

    def test_ai_suggestion_for_newtons_second_law_validates_with_the_same_rules(self):
        provider = FakeAIProvider(response=json.dumps({
            "title": "Reach cruising speed", "description": "d", "instructions": "i",
            "initial_state": {"mass_kg": 2, "force_n": 10},
            "target_kind": "value", "target_field": "velocity_m_s",
            "target_value": 10, "tolerance": 0.5, "at_time_s": 2,
        }))
        draft = services.suggest_scenario_draft(
            teacher_request="Reach a cruising speed.", simulation_id=self.sim.pk, provider=provider,
        )
        self.assertEqual(draft["initial_state"], {"mass_kg": 2.0, "force_n": 10.0})
        self.assertEqual(draft["target_condition"]["field"], "velocity_m_s")

    def test_ai_suggestion_rejects_reverses_for_newtons_second_law(self):
        provider = FakeAIProvider(response=json.dumps({
            "title": "Bad", "description": "d", "instructions": "i",
            "initial_state": {"mass_kg": 2, "force_n": 10},
            "target_kind": "reverses",
        }))
        with self.assertRaises(services.ScenarioError):
            services.suggest_scenario_draft(
                teacher_request="x", simulation_id=self.sim.pk, provider=provider,
            )

    def test_form_shows_mass_and_force_fields_and_hides_reverses_option(self):
        self.client.login(username=self.teacher.username, password=PW)
        body = self.client.post(
            reverse("teachers:scenario_create"),
            {"action": "choose_simulation", "simulation_id": str(self.sim.pk)},
        ).content.decode()
        self.assertIn('id="sf-initial-mass_kg"', body)
        self.assertIn('id="sf-initial-force_n"', body)
        self.assertNotIn('value="reverses"', body)


@override_settings(AI_PROVIDER="fake")
class ScenarioViewSecurityAndCrudTests(TestCase):
    def setUp(self):
        self.sim = _kinematics_sim()
        self.teacher = User.objects.create_user("teach", password=PW, is_staff=True)
        self.other = User.objects.create_user("other_teach", password=PW, is_staff=True)
        self.student_user = User.objects.create_user("pupil", password=PW)

    def _login(self, user):
        self.client.login(username=user.username, password=PW)

    def _make_scenario(self, teacher=None, status=PhysicsScenario.Status.DRAFT, title="Stop the cart"):
        scenario = services.create_scenario(
            teacher=teacher or self.teacher, title=title, simulation_id=self.sim.pk,
            instructions="Bring it to rest.",
            initial_state={"initial_velocity_m_s": 10, "acceleration_m_s2": -2},
            target_condition=_STOP_TARGET,
        )
        if status != PhysicsScenario.Status.DRAFT:
            services.set_scenario_status(scenario_id=scenario.pk, teacher=scenario.created_by, status=status)
            scenario.refresh_from_db()
        return scenario

    def test_anonymous_cannot_access_scenario_routes(self):
        response = self.client.get(reverse("teachers:scenario_list"))
        self.assertEqual(response.status_code, 403)

    def test_student_non_staff_cannot_access_scenario_routes(self):
        self._login(self.student_user)
        response = self.client.get(reverse("teachers:scenario_list"))
        self.assertEqual(response.status_code, 403)

    def test_scenario_list_shows_only_own_scenarios(self):
        mine = self._make_scenario(title="Mine")
        self._make_scenario(teacher=self.other, title="Theirs")
        self._login(self.teacher)
        body = self.client.get(reverse("teachers:scenario_list")).content.decode()
        self.assertIn("Mine", body)
        self.assertNotIn("Theirs", body)

    def test_create_scenario_end_to_end_via_post(self):
        self._login(self.teacher)
        response = self.client.post(
            reverse("teachers:scenario_create"),
            {
                "action": "save",
                "title": "Make the cart stop",
                "simulation_id": str(self.sim.pk),
                "instructions": "Bring it to rest at t = 5 s.",
                "initial_initial_velocity_m_s": "10",
                "initial_acceleration_m_s2": "-2",
                "target_kind": "value",
                "target_field": "velocity_m_s",
                "at_time_s": "5",
                "target_value": "0",
                "tolerance": "0.1",
            },
        )
        scenario = PhysicsScenario.objects.get(title="Make the cart stop")
        self.assertRedirects(response, reverse("teachers:scenario_detail", args=[scenario.slug]))
        self.assertEqual(scenario.created_by_id, self.teacher.id)

    def test_forged_created_by_and_status_in_post_are_ignored(self):
        self._login(self.teacher)
        self.client.post(
            reverse("teachers:scenario_create"),
            {
                "action": "save",
                "title": "Forged owner attempt",
                "simulation_id": str(self.sim.pk),
                "instructions": "x",
                "created_by": str(self.other.pk),
                "status": "active",
                "target_kind": "value", "target_field": "velocity_m_s",
                "at_time_s": "5", "target_value": "0", "tolerance": "0.1",
            },
        )
        scenario = PhysicsScenario.objects.get(title="Forged owner attempt")
        self.assertEqual(scenario.created_by_id, self.teacher.id)
        self.assertEqual(scenario.status, PhysicsScenario.Status.DRAFT)

    def test_edit_another_teachers_scenario_is_404(self):
        scenario = self._make_scenario(teacher=self.other)
        self._login(self.teacher)
        response = self.client.get(reverse("teachers:scenario_edit", args=[scenario.slug]))
        self.assertEqual(response.status_code, 404)

    def test_activate_archive_delete_require_post(self):
        scenario = self._make_scenario()
        self._login(self.teacher)
        for name in ("scenario_activate", "scenario_archive", "scenario_delete"):
            response = self.client.get(reverse(f"teachers:{name}", args=[scenario.slug]))
            self.assertEqual(response.status_code, 405)

    def test_activate_archive_delete_by_other_teacher_is_hidden_not_editable(self):
        # _owned_scenario_or_403 treats "not mine" the same as "does not
        # exist" (404), rather than revealing the scenario exists via a 403 --
        # this also means another teacher can never learn it exists at all.
        scenario = self._make_scenario()
        self._login(self.other)
        for name in ("scenario_activate", "scenario_archive", "scenario_delete"):
            response = self.client.post(reverse(f"teachers:{name}", args=[scenario.slug]))
            self.assertEqual(response.status_code, 404)
        scenario.refresh_from_db()
        self.assertEqual(scenario.status, PhysicsScenario.Status.DRAFT)

    def test_activate_then_appears_in_lab_and_detail(self):
        scenario = self._make_scenario()
        self._login(self.teacher)
        self.client.post(reverse("teachers:scenario_activate", args=[scenario.slug]))
        scenario.refresh_from_db()
        self.assertEqual(scenario.status, PhysicsScenario.Status.ACTIVE)

    def test_xss_in_title_is_escaped_in_list_and_detail(self):
        scenario = self._make_scenario(title="<script>alert(1)</script>")
        self._login(self.teacher)
        list_body = self.client.get(reverse("teachers:scenario_list")).content.decode()
        detail_body = self.client.get(
            reverse("teachers:scenario_detail", args=[scenario.slug])
        ).content.decode()
        self.assertNotIn("<script>alert(1)</script>", list_body)
        self.assertNotIn("<script>alert(1)</script>", detail_body)

    def test_csrf_required_for_mutations(self):
        csrf_client = Client(enforce_csrf_checks=True)
        csrf_client.force_login(self.teacher)
        response = csrf_client.post(
            reverse("teachers:scenario_create"),
            {
                "action": "save", "title": "No CSRF", "simulation_id": str(self.sim.pk),
                "instructions": "x", "target_kind": "value", "target_field": "velocity_m_s",
                "at_time_s": "5", "target_value": "0", "tolerance": "0.1",
            },
        )
        self.assertEqual(response.status_code, 403)
        self.assertFalse(PhysicsScenario.objects.filter(title="No CSRF").exists())

    def test_preview_get_creates_no_records(self):
        scenario = self._make_scenario(status=PhysicsScenario.Status.ACTIVE)
        self._login(self.teacher)
        before = (ExperimentAttempt.objects.count(), LearningEvidence.objects.count())
        self.client.get(reverse("teachers:scenario_detail", args=[scenario.slug]))
        after = (ExperimentAttempt.objects.count(), LearningEvidence.objects.count())
        self.assertEqual(before, after)

    def test_edit_locks_physics_fields_once_used(self):
        scenario = self._make_scenario(status=PhysicsScenario.Status.ACTIVE)
        student = StudentProfile.objects.create(display_name="Alex")
        services.record_scenario_check(student=student, scenario=scenario, met=True, checks=[])
        self._login(self.teacher)
        self.client.post(
            reverse("teachers:scenario_edit", args=[scenario.slug]),
            {
                "title": "Renamed after use",
                "instructions": scenario.instructions,
                "simulation_id": str(self.sim.pk),
                "initial_initial_velocity_m_s": "999",
                "target_kind": "value", "target_field": "velocity_m_s",
                "at_time_s": "5", "target_value": "999", "tolerance": "0.1",
            },
        )
        scenario.refresh_from_db()
        self.assertEqual(scenario.title, "Renamed after use")
        self.assertEqual(scenario.initial_state["initial_velocity_m_s"], 10.0)


class ScenarioStudentFlowTests(TestCase):
    def setUp(self):
        self.sim = _kinematics_sim()
        self.teacher = User.objects.create_user("teach", password=PW, is_staff=True)
        self.scenario = services.create_scenario(
            teacher=self.teacher, title="Stop the cart", simulation_id=self.sim.pk,
            instructions="Bring it to rest at t=5s.",
            initial_state={"initial_velocity_m_s": 10, "acceleration_m_s2": -2},
            target_condition=_STOP_TARGET,
        )
        services.set_scenario_status(
            scenario_id=self.scenario.pk, teacher=self.teacher, status=PhysicsScenario.Status.ACTIVE
        )
        self.scenario.refresh_from_db()
        self.lab_url = reverse("physics_lab:detail", args=[self.sim.slug])
        self.check_url = reverse(
            "physics_lab:experiment_scenario_check",
            args=[self.sim.slug, f"{TEACHER_SCENARIO_PREFIX}{self.scenario.slug}"],
        )

    def test_lab_detail_preselects_scenario_via_query_param(self):
        body = self.client.get(self.lab_url, {"scenario": self.scenario.slug}).content.decode()
        self.assertIn(f'data-selected-scenario="{TEACHER_SCENARIO_PREFIX}{self.scenario.slug}"', body)

    def test_unknown_scenario_query_param_is_ignored(self):
        body = self.client.get(self.lab_url, {"scenario": "does-not-exist"}).content.decode()
        self.assertIn('data-selected-scenario=""', body)

    def test_draft_scenario_query_param_is_ignored(self):
        draft = services.create_scenario(
            teacher=self.teacher, title="Still drafting", simulation_id=self.sim.pk,
            instructions="x", target_condition=_STOP_TARGET,
        )
        body = self.client.get(self.lab_url, {"scenario": draft.slug}).content.decode()
        self.assertIn('data-selected-scenario=""', body)

    def test_teacher_scenario_appears_in_lab_scenario_json(self):
        body = self.client.get(self.lab_url).content.decode()
        self.assertIn(f"{TEACHER_SCENARIO_PREFIX}{self.scenario.slug}", body)

    def test_check_endpoint_evaluates_teacher_scenario(self):
        response = self.client.post(
            self.check_url,
            {"initial_position_m": "0", "initial_velocity_m_s": "10", "acceleration_m_s2": "-2"},
        )
        self.assertEqual(response.status_code, 200)
        self.assertTrue(response.json()["met"])

    def test_check_endpoint_ignores_forged_completion_fields(self):
        response = self.client.post(
            self.check_url,
            {
                "initial_position_m": "0", "initial_velocity_m_s": "1", "acceleration_m_s2": "0",
                "met": "true", "completed": "true", "score": "100",
            },
        )
        self.assertFalse(response.json()["met"])

    def test_draft_scenario_check_endpoint_404s(self):
        draft = services.create_scenario(
            teacher=self.teacher, title="Never activated", simulation_id=self.sim.pk,
            instructions="x", target_condition=_STOP_TARGET,
        )
        url = reverse(
            "physics_lab:experiment_scenario_check",
            args=[self.sim.slug, f"{TEACHER_SCENARIO_PREFIX}{draft.slug}"],
        )
        self.assertEqual(self.client.post(url).status_code, 404)

    def test_evidence_recorded_once_per_check_with_correct_context(self):
        self.client.post(
            self.check_url,
            {"initial_position_m": "0", "initial_velocity_m_s": "10", "acceleration_m_s2": "-2"},
        )
        ev = LearningEvidence.objects.get(kind=LearningEvidence.Kind.EXPERIMENT_OBSERVED)
        self.assertEqual(ev.context["scenario"], self.scenario.slug)
        self.assertEqual(ev.context["simulation"], "kinematics")
        self.assertIs(ev.context["result"], True)
        self.assertEqual(ev.context["attempt_number"], 1)
        self.assertEqual(ExperimentAttempt.objects.count(), 0)

    def test_attempt_number_increments_across_checks(self):
        for _ in range(3):
            self.client.post(
                self.check_url,
                {"initial_position_m": "0", "initial_velocity_m_s": "10", "acceleration_m_s2": "-2"},
            )
        numbers = sorted(
            LearningEvidence.objects.filter(
                kind=LearningEvidence.Kind.EXPERIMENT_OBSERVED
            ).values_list("context__attempt_number", flat=True)
        )
        self.assertEqual(numbers, [1, 2, 3])

    def test_built_in_scenario_check_still_persists_nothing_regression(self):
        url = reverse(
            "physics_lab:experiment_scenario_check", args=[self.sim.slug, "reach-20-at-4"]
        )
        before = LearningEvidence.objects.count()
        self.client.post(
            url, {"initial_position_m": "0", "initial_velocity_m_s": "3", "acceleration_m_s2": "1"}
        )
        self.assertEqual(LearningEvidence.objects.count(), before)


class TeacherScenarioEvidenceTests(TestCase):
    def setUp(self):
        self.sim = _kinematics_sim()
        self.teacher = User.objects.create_user("teach", password=PW, is_staff=True)
        self.student = StudentProfile.objects.create(display_name="Alex")
        self.scenario = services.create_scenario(
            teacher=self.teacher, title="Stop the cart", simulation_id=self.sim.pk,
            instructions="x", target_condition=_STOP_TARGET,
        )
        services.set_scenario_status(
            scenario_id=self.scenario.pk, teacher=self.teacher, status=PhysicsScenario.Status.ACTIVE
        )
        self.scenario.refresh_from_db()

    def test_aggregation_by_scenario_slug(self):
        services.record_scenario_check(student=self.student, scenario=self.scenario, met=False, checks=[])
        services.record_scenario_check(student=self.student, scenario=self.scenario, met=True, checks=[])
        rows = services.get_teacher_scenario_evidence(self.student)
        self.assertEqual(len(rows), 1)
        self.assertEqual(rows[0]["scenario"], "Stop the cart")
        self.assertEqual(rows[0]["attempts"], 2)
        self.assertEqual(rows[0]["latest_result"], "Target achieved")

    def test_no_mastery_or_score_language(self):
        services.record_scenario_check(student=self.student, scenario=self.scenario, met=True, checks=[])
        rows = services.get_teacher_scenario_evidence(self.student)
        blob = json.dumps(rows, default=str).lower()
        for banned in ("mastery", "rank", "score", "grade"):
            self.assertNotIn(banned, blob)

    def test_student_detail_page_renders_scenario_evidence_section(self):
        services.record_scenario_check(student=self.student, scenario=self.scenario, met=True, checks=[])
        self.client.login(username=self.teacher.username, password=PW)
        body = self.client.get(
            reverse("teachers:student_detail", args=[self.student.pk])
        ).content.decode()
        self.assertIn("Stop the cart", body)
        self.assertIn("Target achieved", body)

    def test_no_evidence_row_when_never_run(self):
        self.assertEqual(services.get_teacher_scenario_evidence(self.student), [])


class LessonScenarioIntegrationTests(TestCase):
    def setUp(self):
        from apps.lessons.models import Lesson

        self.sim = _kinematics_sim()
        self.teacher = User.objects.create_user("teach", password=PW, is_staff=True)
        self.other = User.objects.create_user("other_teach", password=PW, is_staff=True)
        self.lesson = Lesson.objects.create(
            title="Kinematics lesson", topic="Kinematics", grade_level="11",
            duration_minutes=45, learning_objectives=["x"],
        )
        self.scenario = services.create_scenario(
            teacher=self.teacher, title="Stop the cart", simulation_id=self.sim.pk,
            instructions="x", target_condition=_STOP_TARGET,
        )
        services.set_scenario_status(
            scenario_id=self.scenario.pk, teacher=self.teacher, status=PhysicsScenario.Status.ACTIVE
        )
        self.scenario.refresh_from_db()

    def test_teacher_can_link_own_active_scenario(self):
        from apps.lessons.authoring_services import create_activity

        activity = create_activity(
            lesson=self.lesson, teacher=self.teacher, activity_type="scenario",
            title="Try the challenge", reference_id=self.scenario.pk,
        )
        self.assertEqual(activity.scenario_id, self.scenario.pk)

    def test_teacher_cannot_link_another_teachers_scenario(self):
        from apps.lessons.authoring_services import LessonAuthoringError, create_activity

        with self.assertRaises(LessonAuthoringError):
            create_activity(
                lesson=self.lesson, teacher=self.other, activity_type="scenario",
                title="Try the challenge", reference_id=self.scenario.pk,
            )

    def test_cannot_link_a_draft_scenario(self):
        from apps.lessons.authoring_services import LessonAuthoringError, create_activity

        draft = services.create_scenario(
            teacher=self.teacher, title="Still drafting", simulation_id=self.sim.pk,
            instructions="x", target_condition=_STOP_TARGET,
        )
        with self.assertRaises(LessonAuthoringError):
            create_activity(
                lesson=self.lesson, teacher=self.teacher, activity_type="scenario",
                title="Try it", reference_id=draft.pk,
            )

    def test_cannot_link_scenario_whose_simulation_is_now_inactive(self):
        from apps.lessons.authoring_services import LessonAuthoringError, create_activity

        self.sim.is_active = False
        self.sim.save(update_fields=["is_active"])
        with self.assertRaises(LessonAuthoringError):
            create_activity(
                lesson=self.lesson, teacher=self.teacher, activity_type="scenario",
                title="Try it", reference_id=self.scenario.pk,
            )

    def test_student_launch_url_opens_scenario_with_query_param(self):
        from apps.lessons.authoring_services import _student_launch, create_activity

        activity = create_activity(
            lesson=self.lesson, teacher=self.teacher, activity_type="scenario",
            title="Try the challenge", reference_id=self.scenario.pk,
        )
        url, label = _student_launch(activity, self.lesson)
        self.assertEqual(label, "Open the Scenario")
        self.assertIn(reverse("physics_lab:detail", args=[self.sim.slug]), url)
        self.assertIn(f"scenario={self.scenario.slug}", url)


@override_settings(AI_PROVIDER="fake")
class ScenarioAiSuggestionTests(TestCase):
    def setUp(self):
        self.sim = _kinematics_sim()
        self.teacher = User.objects.create_user("teach", password=PW, is_staff=True)

    def test_fake_provider_returns_valid_suggestion_dict(self):
        draft = services.suggest_scenario_draft(
            teacher_request="Make a scenario where a cart stops.", simulation_id=self.sim.pk,
        )
        self.assertIn("title", draft)
        self.assertIn("target_condition", draft)
        self.assertEqual(draft["simulation_id"], self.sim.pk)

    def test_suggestion_persists_nothing(self):
        before = PhysicsScenario.objects.count()
        services.suggest_scenario_draft(
            teacher_request="Make a scenario where a cart stops.", simulation_id=self.sim.pk,
        )
        self.assertEqual(PhysicsScenario.objects.count(), before)

    def test_missing_teacher_request_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services.suggest_scenario_draft(teacher_request="   ", simulation_id=self.sim.pk)

    def test_invalid_ai_simulation_is_rejected(self):
        with self.assertRaises(services.ScenarioError):
            services.suggest_scenario_draft(teacher_request="x", simulation_id=999999)

    def test_invalid_ai_target_field_is_rejected_same_as_manual_input(self):
        bad_provider = FakeAIProvider(response=json.dumps({
            "title": "Bad", "description": "d", "instructions": "i",
            "initial_state": {"initial_velocity_m_s": 5},
            "target_kind": "value", "target_field": "warp_factor",
            "target_value": 0, "tolerance": 1, "at_time_s": 5,
        }))
        with self.assertRaises(services.ScenarioError):
            services.suggest_scenario_draft(
                teacher_request="x", simulation_id=self.sim.pk, provider=bad_provider
            )

    def test_invalid_ai_out_of_range_parameter_is_rejected(self):
        bad_provider = FakeAIProvider(response=json.dumps({
            "title": "Bad", "description": "d", "instructions": "i",
            "initial_state": {"acceleration_m_s2": 999},
            "target_kind": "value", "target_field": "velocity_m_s",
            "target_value": 0, "tolerance": 1, "at_time_s": 5,
        }))
        with self.assertRaises(services.ScenarioError):
            services.suggest_scenario_draft(
                teacher_request="x", simulation_id=self.sim.pk, provider=bad_provider
            )

    def test_non_json_ai_response_is_rejected(self):
        bad_provider = FakeAIProvider(response="not json at all")
        with self.assertRaises(services.ScenarioError):
            services.suggest_scenario_draft(
                teacher_request="x", simulation_id=self.sim.pk, provider=bad_provider
            )

    def test_view_ai_suggest_action_renders_draft_without_saving(self):
        self.client.login(username=self.teacher.username, password=PW)
        before = PhysicsScenario.objects.count()
        response = self.client.post(
            reverse("teachers:scenario_create"),
            {
                "action": "ai_suggest", "simulation_id": str(self.sim.pk),
                "teacher_request": "Make the cart stop.",
            },
        )
        self.assertEqual(response.status_code, 200)
        self.assertEqual(PhysicsScenario.objects.count(), before)
        self.assertIn("AI suggestion", response.content.decode())

    def test_ai_draft_still_requires_explicit_save_to_persist(self):
        self.client.login(username=self.teacher.username, password=PW)
        draft = services.suggest_scenario_draft(
            teacher_request="Make the cart stop.", simulation_id=self.sim.pk,
        )
        post_data = {
            "action": "save",
            "title": draft["title"],
            "simulation_id": str(draft["simulation_id"]),
            "instructions": draft["instructions"],
            "target_kind": draft["target_condition"]["kind"],
            "target_field": draft["target_condition"].get("field", ""),
            "at_time_s": str(draft["target_condition"].get("at_time_s", 0)),
            "target_value": str(draft["target_condition"].get("target", 0)),
            "tolerance": str(draft["target_condition"].get("tolerance", 0)),
        }
        for field, value in draft["initial_state"].items():
            post_data[f"initial_{field}"] = str(value)
        response = self.client.post(reverse("teachers:scenario_create"), post_data)
        scenario = PhysicsScenario.objects.get(title=draft["title"])
        self.assertRedirects(response, reverse("teachers:scenario_detail", args=[scenario.slug]))


class ScenarioAccessibilityTests(TestCase):
    def setUp(self):
        self.sim = _kinematics_sim()
        self.teacher = User.objects.create_user("teach", password=PW, is_staff=True)
        self.client.login(username=self.teacher.username, password=PW)

    def test_create_form_has_labels_and_one_heading(self):
        body = self.client.get(reverse("teachers:scenario_create")).content.decode()
        self.assertEqual(body.count("<h1"), 1)
        for input_id in ("sf-title", "sf-instructions", "sf-simulation"):
            self.assertIn(f'for="{input_id}"', body)
            self.assertIn(f'id="{input_id}"', body)
        self.assertIn("<fieldset", body)
        self.assertIn("<legend>", body)

    def test_target_builder_fields_are_labelled(self):
        body = self.client.post(
            reverse("teachers:scenario_create"),
            {"action": "choose_simulation", "simulation_id": str(self.sim.pk)},
        ).content.decode()
        for input_id in ("sf-target-kind", "sf-target-field", "sf-at-time", "sf-target-value"):
            self.assertIn(f'for="{input_id}"', body)

    def test_list_and_detail_pages_have_headings(self):
        scenario = services.create_scenario(
            teacher=self.teacher, title="Stop the cart", simulation_id=self.sim.pk,
            instructions="x", target_condition=_STOP_TARGET,
        )
        list_body = self.client.get(reverse("teachers:scenario_list")).content.decode()
        detail_body = self.client.get(
            reverse("teachers:scenario_detail", args=[scenario.slug])
        ).content.decode()
        self.assertEqual(list_body.count("<h1"), 1)
        self.assertEqual(detail_body.count("<h1"), 1)
        self.assertIn("<h2", detail_body)

    def test_error_message_uses_alert_role(self):
        response = self.client.post(
            reverse("teachers:scenario_create"),
            {"action": "save", "title": "", "simulation_id": str(self.sim.pk), "instructions": ""},
        )
        self.assertIn('role="alert"', response.content.decode())
