# Generated by Django 5.2.17 on 2026-08-26 22:40

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lesson',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('topic', models.CharField(max_length=255)),
                ('grade_level', models.CharField(help_text='e.g., 9, 10, 11, 12', max_length=50)),
                ('description', models.TextField(blank=True)),
                ('objectives', models.JSONField(default=list, help_text='Learning objectives')),
                ('prerequisites', models.JSONField(default=list, help_text='Prerequisite knowledge')),
                ('difficulty', models.IntegerField(choices=[(1, 'Beginner'), (2, 'Easy'), (3, 'Intermediate'), (4, 'Advanced'), (5, 'Expert')], default=1)),
                ('content', models.JSONField(default=dict, help_text='Generated lesson content')),
                ('problems', models.JSONField(default=list, help_text='Practice problems')),
                ('misconceptions', models.JSONField(default=list, help_text='Common misconceptions')),
                ('ai_generated', models.BooleanField(default=False)),
                ('ai_model', models.CharField(blank=True, max_length=50, null=True)),
                ('ai_version', models.CharField(blank=True, max_length=20, null=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('review', 'Under Review'), ('approved', 'Approved'), ('published', 'Published'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('published_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_lessons', to=settings.AUTH_USER_MODEL)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='LessonFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField(choices=[(1, 'Poor'), (2, 'Fair'), (3, 'Good'), (4, 'Very Good'), (5, 'Excellent')])),
                ('comment', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback', to='lessons.lesson')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['status'], name='lessons_les_status_ff86f9_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['topic'], name='lessons_les_topic_251e48_idx'),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['grade_level'], name='lessons_les_grade_l_8ef4c3_idx'),
        ),
    ]
