# Generated by Django 5.2.17 on 2026-08-26 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0002_lesson_physics_concepts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='common_misconceptions',
            field=models.JSONField(default=list, help_text='Lesson-specific misconceptions to address.'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='learning_objectives',
            field=models.JSONField(default=list, help_text='Learning objectives for this lesson.'),
        ),
    ]
