# Generated by Django 5.2.17 on 2026-09-08 20:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assessments', '0001_initial'),
        ('lessons', '0003_alter_lesson_common_misconceptions_and_more'),
        ('physics', '0005_misconceptionrecoverypath_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LessonActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('position', models.PositiveSmallIntegerField(help_text='1-based order within the lesson.')),
                ('activity_type', models.CharField(choices=[('explanation', 'Explanation'), ('physics_lab', 'Physics Lab'), ('practice', 'Practice question'), ('tutor', 'Tutor discussion'), ('assessment', 'Assessment'), ('recovery', 'Misconception recovery')], max_length=32)),
                ('title', models.CharField(max_length=200)),
                ('instructions', models.TextField(blank=True, default='', help_text='Concise teacher guidance shown to the student for this step.')),
                ('tutor_focus', models.CharField(blank=True, default='', help_text='Optional safe instructional focus for a tutor activity.', max_length=200)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assessment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assessments.assessment')),
                ('lesson', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='lessons.lesson')),
                ('question', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='assessments.questionbankitem')),
                ('recovery_path', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='physics.misconceptionrecoverypath')),
                ('simulation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='physics.physicssimulation')),
            ],
            options={
                'verbose_name': 'Lesson activity',
                'verbose_name_plural': 'Lesson activities',
                'ordering': ['lesson', 'position', 'id'],
                'constraints': [models.UniqueConstraint(fields=('lesson', 'position'), name='uniq_lesson_activity_position')],
            },
        ),
    ]
