# Generated by Django 5.2.17 on 2026-09-19 19:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0004_lessonactivity'),
        ('physics', '0026_alter_physicssimulation_simulation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='level',
            field=models.CharField(blank=True, choices=[('discovery', 'Physics Discovery'), ('foundation', 'Foundation'), ('junior_high', 'Junior High'), ('senior_high', 'Senior High'), ('intro_university', 'Introductory University'), ('intermediate_university', 'Intermediate University'), ('advanced_undergraduate', 'Advanced Undergraduate'), ('graduate_prep', 'Graduate Preparation')], default='', help_text='Optional physics depth level this lesson targets (from the level taxonomy) -- distinct from grade_level, since the same school grade can be taught at different physics depths.', max_length=30),
        ),
        migrations.AddIndex(
            model_name='lesson',
            index=models.Index(fields=['level'], name='lessons_les_level_7034dc_idx'),
        ),
    ]
