# Generated by Django 5.2.17 on 2026-09-20 08:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lessons', '0005_lesson_level_lesson_lessons_les_level_7034dc_idx'),
        ('physics', '0027_physicsscenario'),
    ]

    operations = [
        migrations.AddField(
            model_name='lessonactivity',
            name='scenario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='physics.physicsscenario'),
        ),
        migrations.AlterField(
            model_name='lessonactivity',
            name='activity_type',
            field=models.CharField(choices=[('explanation', 'Explanation'), ('physics_lab', 'Physics Lab'), ('practice', 'Practice question'), ('tutor', 'Tutor discussion'), ('assessment', 'Assessment'), ('recovery', 'Misconception recovery'), ('scenario', 'Physics Scenario')], max_length=32),
        ),
    ]
